config/routes.rb
Rails.application.routes.draw do
  resources :video_chats
  resources :projects
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :home_pages


  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  root 'home_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home_page.rb
class HomePage < ApplicationRecord

    has_many_attached :images
    
end

app/models/project.rb
class Project < ApplicationRecord

    has_many_attached :images
    has_rich_text :description

end
 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { user: 0, admin: 1}
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end 
end

app/models/video_chat.rb
class VideoChat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    def after_sign_out_path_for scope
        root_path
      end

      
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  before_action :set_home_page, only: %i[ show edit update destroy ]

  # GET /home_pages or /home_pages.json
  def index
    @home_pages = HomePage.all
  end

  # GET /home_pages/1 or /home_pages/1.json
  def show
  end

  # GET /home_pages/new
  def new
    @home_page = HomePage.new
  end

  # GET /home_pages/1/edit
  def edit
  end

  # POST /home_pages or /home_pages.json
  def create
    @home_page = HomePage.new(home_page_params)

    respond_to do |format|
      if @home_page.save
        format.html { redirect_to home_page_url(@home_page), notice: "Home page was successfully created." }
        format.json { render :show, status: :created, location: @home_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /home_pages/1 or /home_pages/1.json
  def update
    respond_to do |format|
      if @home_page.update(home_page_params)
        format.html { redirect_to home_page_url(@home_page), notice: "Home page was successfully updated." }
        format.json { render :show, status: :ok, location: @home_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /home_pages/1 or /home_pages/1.json
  def destroy
    @home_page.destroy

    respond_to do |format|
      format.html { redirect_to home_pages_url, notice: "Home page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home_page
      @home_page = HomePage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_page_params
      params.require(:home_page).permit(:title, :description, images: [] )
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :repo_link, :deployed_link, images: [])
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/video_chats_controller.rb
class VideoChatsController < ApplicationController
  before_action :set_video_chat, only: %i[ show edit update destroy ]

  # GET /video_chats or /video_chats.json
  def index
    @video_chats = VideoChat.all
  end

  # GET /video_chats/1 or /video_chats/1.json
  def show
  end

  # GET /video_chats/new
  def new
    @video_chat = VideoChat.new
  end

  # GET /video_chats/1/edit
  def edit
  end

  # POST /video_chats or /video_chats.json
  def create
    @video_chat = VideoChat.new(video_chat_params)

    respond_to do |format|
      if @video_chat.save
        format.html { redirect_to video_chat_url(@video_chat), notice: "Video chat was successfully created." }
        format.json { render :show, status: :created, location: @video_chat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video_chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_chats/1 or /video_chats/1.json
  def update
    respond_to do |format|
      if @video_chat.update(video_chat_params)
        format.html { redirect_to video_chat_url(@video_chat), notice: "Video chat was successfully updated." }
        format.json { render :show, status: :ok, location: @video_chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video_chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_chats/1 or /video_chats/1.json
  def destroy
    @video_chat.destroy

    respond_to do |format|
      format.html { redirect_to video_chats_url, notice: "Video chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_chat
      @video_chat = VideoChat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_chat_params
      params.require(:video_chat).permit(:name, :session)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/video_chats_helper.rb
module VideoChatsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home_pages/_form.html.erb
<%= form_with(model: home_page) do |form| %>
  <% if home_page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(home_page.errors.count, "error") %> prohibited this home_page from being saved:</h2>

      <ul>
        <% home_page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="m-2">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="m-2">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, style: "width: 375px; height: 400px;" %>
  </div>

  <div class="m-2">
    <%= form.file_field :images, multiple:true %>
  </div>

  <br>
  
  <div class="m-2">
    <%= form.submit %>
  </div>
<% end %>

app/views/home_pages/_home_page.html.erb
<div id="<%= dom_id home_page %>"  class:"nav-link text-white">

  <div class="">
    <% if user_signed_in? %>
      <% if current_user.admin? %>
      <% end %>
    <% end %>
  </div>
</div>


<div class="container">
  <div class="row my-5">
    <div class="col-sm-12 col-md-6 p-0 px-2">
      <div class="m-2">
        <h1>
          <%= home_page.title  %>
        </h1>
      </div>
      
      <div class="m-2">
        <h6>
        <%= home_page.description %>
        </h6>
      </div>
    </div>

    <div class="col-sm-12 col-md-6 p-0 ">
      <div class="images d-flex justify-content-center ">
        <% home_page.images.each do |image| %>
          <%= image_tag(image, style: "max-width: 95%;") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home_pages/edit.html.erb
<h1 class="text-white m-2">Editing home page</h1>

<div class="text-white">
<%= render "form", home_page: @home_page %>
</div>

<br>

<div class="nav-link m-2">
  <%= link_to "Show this home page", @home_page %> |
  <%= link_to "Back to home pages", home_pages_path %>
</div>

app/views/home_pages/index.html.erb
<p style="color: green" class="m-2"><%= notice %></p>

<% if user_signed_in? %>

  <p class="m-2">
    <%= link_to "New home page", new_home_page_path if current_user.admin? %>
  </p>  
<% end %>  

<div id="home_pages" class="text-white">
  <% @home_pages.each do |home_page| %>
    <%= render home_page %>
</div>
  
  <% if user_signed_in? %>
    <p class="m-2">
      <%= link_to "Show this home page", home_page if current_user.admin? %>
    </p>
    
  <% end %>

<%end %>

app/views/home_pages/new.html.erb
<h1 class="text-white m-2">New home page</h1>

<div class="text-white">
<%= render "form", home_page: @home_page %>
</div>

<br>


<div>
  <%= link_to "Back to home pages", home_pages_path if current_user.admin? %>
</div>

app/views/home_pages/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="text-white">
  <%= render @home_page %>
</div>


<div class="m-2">
  <%= link_to "Edit this home page", edit_home_page_path(@home_page) %> |
  <%= link_to "Back to home pages", home_pages_path %>

  <%= button_to "Destroy this home page", @home_page, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "navbar" %>

<nav class="navbar navbar-dark navbar-expand-lg bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand text-white" id="navTitle" href="/">David Healy</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Home", home_pages_path, class:"nav-link text-white" %>
        </li>

        <li class="nav-item">
            <%= link_to "Portfolio", projects_path, class:"nav-link text-white" %>
        </li>

        <li class="nav-item">
            <%= link_to "Video Chat", video_chats_path, class:"nav-link text-white" %>
        </li>
      </ul>
      <div>
      <% if user_signed_in? %>
      <li class="d-flex align-self-center">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :get, class:"nav-link text-white" %>
          </li>
          <li class="nav-item">
              <%= link_to "Admin", rails_admin_path, class:"nav-link text-white" if current_user.admin? %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class:"nav-link text-white" %>
          </li>
        </ul>
      <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>David Healy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('app/assets/favicon/favicon.ico') %>
    <%= stylesheet_link_tag "styles" %>
    <%= stylesheet_link_tag "images" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    
  </head>

  <body class="bg-dark" >
    <header>
    <%= render "layouts/navbar" %>
    </header>
    <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul as="style">
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="m-2">
    <div class="text-white m-2">
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>


    <div class=" col-10 bg-white m-2 field">
      <%= form.label :description, style: "display: block" %>
      <%= form.rich_text_area :description, style: "height: 400px" %>
    </div>


    <div class="text-white m-2">
      <%= form.label :repo_link, style: "display: block" %>
      <%= form.text_area :repo_link %>
    </div>

    <div class="text-white m-2">
      <%= form.label :deployed_link, style: "display: block" %>
      <%= form.text_area :deployed_link %>
    </div>

    <div class="m-2">
    <%= form.file_field :images, multiple:true %>
    </div>

    <div class="m-2" as="style">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>" class="text-white">

<%= stylesheet_link_tag "projects", "data-turbo-track": "reload" %>

  <div class="container">
    <div class="row my-5">
      <div class="col-sm-12 col-md-6 p-0 px-2">
        <div class="m-2 my-3">
          <h1 class="fs-1">
            <%= project.title %>
          </h1>
        </div>
      </div>

      <div class="col-sm-12 col-md-6 p-0 ">
        <div class="images d-flex justify-content-center">
          <% project.images.each do |image| %>
            <%= image_tag(image, style: "width: 100%;") %>
          <% end %>
        </div>
      </div>
      
      <div class="m-2">
        <div class="row">
          <div class="d-flex justify-content-around">
            <a href="<%= project.repo_link %>" 
                class="btn btn-dark" 
                tabindex="-1" 
                role="button" 
                aria-disabled="true"
                target="blank">
                Repo Link
            </a>
            <a href="<%= project.deployed_link %>" 
                class="btn btn-dark" 
                tabindex="-1" 
                role="button" 
                aria-disabled="true"
                target="blank">
                Deployed App
            </a>
            <div class="btn btn-dark">
            <%= link_to "Show This Project", project , style: "color: white; text-decoration: none; align-self: center;"%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1 class="text-white">Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> 
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-white mx-3">Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
  <% end %>
</div>
  <div class="m-2">
    <% if user_signed_in? %>
      <%= link_to "New project", new_project_path if current_user.admin?%>
    <% end %>
  </div>

app/views/projects/new.html.erb
<h1 class="text-white m-2">New project</h1>

<%= render "form", project: @project %>

<br>

<div class="m-2">
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

  <div class="text-white m-3">
    <%= @project.description %>
  </div>

  <% if user_signed_in? %>
    <div class="m-2">
      <%= link_to "Edit this project", edit_project_path(@project) if current_user.admin? %> |
      <%= link_to "Back to projects", projects_path if current_user.admin? %>

      <%= button_to "Destroy this project", @project, method: :delete if current_user.admin? %>
    </div>
  <% end %>

app/views/video_chats/_form.html.erb
<%= form_with(model: video_chat) do |form| %>
  <% if video_chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(video_chat.errors.count, "error") %> prohibited this video_chat from being saved:</h2>

      <ul>
        <% video_chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mx-4">
    <div class="text-white">
      <%= form.label :message, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/video_chats/_video_chat.html.erb
<div id="<%= dom_id video_chat %>" class="text-white" as="style">
  <p>
    <%= video_chat.name %>
  </p>


<div class="embedVideoContainer d-flex justify-content-center my-3">
  <div id="otEmbedContainer" style="width:800px; height:640px" as="style"></div>
    <script src="https://tokbox.com/embed/embed/ot-embed.js?embedId=bb1853cf-54ac-4957-896e-32b937862107&room=DEFAULT_ROOM"></script>
  </div>
</div>

app/views/video_chats/edit.html.erb
<h1 class="text-white mx-2">Editing video chat</h1>


<%= render "form", video_chat: @video_chat %>

<br>

<div class="m-2">
  <%= link_to "Show this video chat", @video_chat %> |
  <%= link_to "Back to video chats", video_chats_path %>
</div>

app/views/video_chats/index.html.erb
<div class="m-2">
  <p style="color: green"><%= notice %></p>
</div>

<h1 class="text-white mx-2">Video chats</h1>

<div id="video_chats">
  <% @video_chats.each do |video_chat| %>
    <%= render video_chat %>
    <p>
      <%= link_to "Show this video chat", video_chat %>
    </p>
  <% end %>
</div>

<div class="mx-2" as="style">
<% if user_signed_in? %>
  <%= link_to "New video chat", new_video_chat_path if current_user.admin? %>
<% end %>
</div>

app/views/video_chats/new.html.erb
<h1 class="text-white m-2">New video chat</h1>


<div class="mx-2">
  <%= render "form", video_chat: @video_chat %>
</div>
<br>

<div class="mx-4">
  <%= link_to "Back to video chats", video_chats_path %>
</div>

app/views/video_chats/show.html.erb
<div class="m-2">
<p style="color: green"><%= notice %></p>
</div>

<%= render @video_chat %>

<div class="mx-4 mb-2">
  <%= link_to "Edit this video chat", edit_video_chat_path(@video_chat) %> |
  <%= link_to "Back to video chats", video_chats_path %>

  <%= button_to "Destroy this video chat", @video_chat, method: :delete %>
</div>